name = "devOS Modpack"
author = "devOS-Nautical"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9885d6edc7972aca437c5599f681450c6da76a6f2d6b18c086230d69718bf226"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"
