name = "devOS Season 5"
author = "devOS-Nautical"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f219973ac98f8d24784e5475cb9bcbce7cd803a30415fb630e0f9b509f09efa"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
