name = "Dev OS Modpack"
author = "devOS-Nautical"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "273babbb540afc3b360a25d9e16d0a919b2716d68d26959dbcf57fe1a459bd68"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"
