name = "devOS Modpack"
author = "devOS-Nautical"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3991127753fdd62b4810110e2bff3a9fc8662ba3a0986c8e91542bf316c22f9e"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"
