name = "devOS-Modpack-Server"
author = "devOS-Nautical"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d47e634cebf8226c5afe97ffc4c11e30fe6ce53defdfe049cb2ccd19e68463ae"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"
