name = "devOS-Modpack-Server"
author = "devOS-Nautical"
version = "h.h.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17b9d14d2e1559117089e682a601fab656107a82d08f5854a3ead80f0d0e987f"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"
